name: Azure Login

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Top level permissions are important
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  azure-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        if: success()
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'