name: deploy pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  setup-terraform-state:
    runs-on: ubuntu-latest
    environment: tenant00
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      TF_VAR_location: ${{ vars.LOCATION }}
      TF_VAR_tenant_shortname: ${{ vars.TENANT_SHORTNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Azure Login
        if: success()
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.0'
    
      - name: Create and Format Backend Configuration
        run: |
          # Debug: Show initial directory structure
          echo "Current directory structure:"
          pwd
          ls -R
          
          # Create terraform directory if it doesn't exist
          mkdir -p terraform
          
          # Copy all files from the modules directory
          cp -r ./terraform/modules/resource_group/* terraform/
          
          # Create backend.tf in the terraform directory
          cat > terraform/backend.tf << 'EOF'
          terraform {
            backend "azurerm" {
              resource_group_name  = "terraform-state-rg"
              storage_account_name = "tfstatemftfb413"
              container_name      = "tfstate"
              key                 = "terraform.tfstate"
            }
          }
          EOF
          
          # Format the files
          cd terraform
          terraform fmt
          
          # Debug: Show final contents
          echo "Final terraform directory contents:"
          ls -la

      - name: 'Terraform Init'
        working-directory: ./terraform
        run: terraform init
    
      - name: 'Terraform Format Check'
        working-directory: ./terraform
        run: |
          terraform fmt -check
          if [ $? -eq 0 ]; then
            echo "Formatting check passed"
          else
            echo "Formatting issues found"
            exit 1
          fi
      
      - name: 'Terraform Plan'
        id: plan
        working-directory: ./terraform
        run: |
          echo "Starting Terraform plan at $(date)"
          
          # Run plan with detailed exit code
          set +e
          terraform plan -detailed-exitcode -out=tfplan
          PLAN_EXIT_CODE=$?
          set -e
          
          echo "Plan exit code: $PLAN_EXIT_CODE"
          
          # More verbose output for debugging
          if [ $PLAN_EXIT_CODE -eq 0 ]; then
            echo "No changes detected"
          elif [ $PLAN_EXIT_CODE -eq 1 ]; then
            echo "Terraform plan failed"
            exit 1
          elif [ $PLAN_EXIT_CODE -eq 2 ]; then
            echo "Changes detected"
          fi
          
          # Set output with more debugging
          echo "Setting output: exit_code=$PLAN_EXIT_CODE"
          echo "exit_code=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT
          
          # Also set environment variable as backup
          echo "PLAN_EXIT_CODE=$PLAN_EXIT_CODE" >> $GITHUB_ENV

      - name: 'Terraform Apply'
        if: |
          github.ref == 'refs/heads/main' && 
          (steps.plan.outputs.exit_code == '2' || env.PLAN_EXIT_CODE == '2')
        working-directory: ./terraform
        run: |
          echo "Debug: Current branch is ${{ github.ref }}"
          echo "Debug: Plan exit code from output is ${{ steps.plan.outputs.exit_code }}"
          echo "Debug: Plan exit code from env is ${{ env.PLAN_EXIT_CODE }}"
          
          if [ -f tfplan ]; then
            echo "Changes detected, applying..."
            terraform apply -auto-approve tfplan
          else
            echo "No plan file found!"
            exit 1
          fi

      - name: 'Verify State'
        working-directory: ./terraform
        if: success() && github.ref == 'refs/heads/main'
        run: |
          echo "Verifying state file creation..."
          terraform state list