name: Azure Login

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  azure-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Azure Login
        if: success()
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.0'
    
      - name: Create and Format Backend Configuration
        run: |
          # Create terraform directory
          mkdir -p terraform
          
          # Create backend.tf in the terraform directory
          cat > terraform/backend.tf << 'EOF'
          terraform {
            backend "azurerm" {
              resource_group_name  = "terraform-state-rg"
              storage_account_name = "tfstatemftfb413"
              container_name      = "tfstate"
              key                 = "terraform.tfstate"
            }
          }
          EOF
          
          # Format the file
          cd terraform
          terraform fmt backend.tf
          
          # Print the formatted content
          cat backend.tf