name: 'Terraform Azure Deployment'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret Status
      run: |
        echo "Testing if secrets exist:"
        if [[ -n "${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }}" ]]; then echo "AZURE_CREDENTIALS_CLIENT_ID exists"; else echo "AZURE_CREDENTIALS_CLIENT_ID is missing"; fi
        if [[ -n "${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }}" ]]; then echo "AZURE_CREDENTIALS_CLIENT_SECRET exists"; else echo "AZURE_CREDENTIALS_CLIENT_SECRET is missing"; fi
        if [[ -n "${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}" ]]; then echo "AZURE_CREDENTIALS_SUBSCRIPTION_ID exists"; else echo "AZURE_CREDENTIALS_SUBSCRIPTION_ID is missing"; fi
        if [[ -n "${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}" ]]; then echo "AZURE_CREDENTIALS_TENANT_ID exists"; else echo "AZURE_CREDENTIALS_TENANT_ID is missing"; fi

    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}