name: 'Terraform Azure Deployment'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production     # Add this line to specify environment
    
    steps:
    - name: Verify Secret Availability
      run: |
        echo "Verifying required secrets..."
        for secret in "CLIENTID" "CLIENTSECRET" "SUBSCRIPTIONID" "TENANTID"; do
          if [[ -z "${!secret}" ]]; then
            echo "::error::${secret} is not set"
            exit 1
          fi
        done
      env:
        CLIENTID: ${{ secrets.CLIENTID }}
        CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
        SUBSCRIPTIONID: ${{ secrets.SUBSCRIPTIONID }}
        TENANTID: ${{ secrets.TENANTID }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Azure Login'
      uses: azure/login@v1
      env:
        AZURE_CREDS: '{"clientId":"${{ secrets.CLIENTID }}","clientSecret":"${{ secrets.CLIENTSECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTIONID }}","tenantId":"${{ secrets.TENANTID }}"}'
      with:
        creds: ${{ env.AZURE_CREDS }}
        enable-AzPSSession: false
        auth-type: SERVICE_PRINCIPAL