name: Azure Login

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Top level permissions are important
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  azure-login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Workflow Permissions
        run: |
          echo "Checking GitHub Actions permissions..."
          
          # Check if we can read repository contents
          echo "Testing repository read access..."
          curl -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }} || echo "Cannot access repository"
          
          # Check if we can read org variables
          echo "Testing organization variables access..."
          echo "AZURE_CLIENT_ID defined: ${{ vars.AZURE_CLIENT_ID != '' }}"
          echo "AZURE_SUBSCRIPTION_ID defined: ${{ vars.AZURE_SUBSCRIPTION_ID != '' }}"
          echo "AZURE_TENANT_ID defined: ${{ vars.AZURE_TENANT_ID != '' }}"
          
          # Check token permissions
          echo "Token Permissions:"
          curl -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/permissions || echo "Cannot check permissions"

      - name: Validate Azure Credentials
        run: |
          echo "Checking CLIENTID..."
          if [[ -n "${{ vars.AZURE_CLIENT_ID }}" ]]; then
            echo "CLIENTID is present: ${AZURE_CLIENT_ID}"
            echo "client_id=${{ vars.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          else
            echo "::error::CLIENTID is missing"
            exit 1
          fi

          echo "Checking CLIENTSECRET..."
          if [[ -n "${{ secrets.AZURE_CLIENT_SECRET }}" ]]; then
            echo "CLIENTSECRET is present"
            echo "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          else
            echo "::error::CLIENTSECRET is missing"
            exit 1
          fi

          echo "Checking SUBSCRIPTIONID..."
          if [[ -n "${{ vars.AZURE_SUBSCRIPTION_ID }}" ]]; then
            echo "SUBSCRIPTIONID is present"
            echo "subscription_id=${{ vars.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          else
            echo "::error::SUBSCRIPTIONID is missing"
            exit 1
          fi

          echo "Checking TENANTID..."
          if [[ -n "${{ vars.AZURE_TENANT_ID }}" ]]; then
            echo "TENANTID is present"
            echo "tenant_id=${{ vars.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          else
            echo "::error::TENANTID is missing"
            exit 1
          fi

      - name: Azure Login
        if: success()
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'