name: Azure Login

on:
  workflow_call:  # Makes this workflow reusable

permissions:
  id-token: write # Required for Azure login
  contents: read  # Required for basic repository access

jobs:
  azure-login:
    runs-on: ubuntu-latest
    environment: production  # Optional: specify deployment environment
    
    # Optional: Configure runner specifications
    strategy:
      matrix:
        node-version: [18.x]  # Specify Node.js version if needed
      fail-fast: false  # Continue with other jobs if one fails
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'